### PR TITLE
AddingPowerSupport_&_CI/Testing

### PR DESCRIPTION
**Pull request by santosh653**
Adding Power Support.

Adding power support ppc64le with Continues Integration/testing so that code remains architecture independent.

This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

The build is successful on both arch: amd64/ppc64le, please find the Travis Link below.
https://travis-ci.com/github/santosh653/goconvey

Please let me know if you need any further details? or if I am missing any.

Thank You !!

### CODE REVIEW

**Comment by santosh653** [comment]
A Gentle Nudge, Checking if you have any further queries on this PR.,

**Comment by santosh653** [comment]
A gently reminder to Let us know if you have any further queries on this PR?

**Comment by santosh653** [comment]
A Gentle Nudge, are there any open queries on this PR?

**Comment by santosh653** [comment]
Once again checking if there are any other queries on this PR.
Thank you !!

**Comment by santosh653** [comment]
Are there any queries open on this PR?

**Comment by gernotstarke** [comment]
is it only MY impression, that this project seems to be stale? Not many reactions by the maintainers, sigh...

**Comment by santosh653** [comment]
Is this PR getting merged?

**Comment by riannucci** [comment]
Sorry this has sat so long... I think I may be the only maintainer left at this point and I had some family matters october -> january.

**Pull request merged**
