### PR TITLE
codebeat badge

### PR DESCRIPTION
**Pull request by korzonek**
Is it fine to add codebeat badge to README? 

codebeat is automated code review tool for Swift, Ruby & Go that helps get instant feedback on code quality. 

"Quick wins" suggested by codebeat could be a nice candidate for a pull request and help other developers become contributors.

FYI. To be fully open and honest. I'm co-founder of codebeat.

### CODE REVIEW

**Comment by mdwhatcott** [comment]
Thanks for introducing me to your shiny new tool! Very nice work. I'm not sure if we want this in the readme or not. Stay tuned.

**Comment by korzonek** [comment]
Thank you! We put a lot of love, passion and code to codebeat. I'm happy you like it. Thx!

**Comment by VorT3x** [comment]
@riannucci @mdwhatcott let's close this PR.

**Comment by korzonek** [comment]
:disappointed: 

@VorT3x @riannucci @mdwhatcott if you have ideas what we could do to improve codebeat please share it with us. We launched in January this year and feedback helps us prioritise things.

**Comment by VorT3x** [comment]
There are tons of such projects, but why we need them all in our Readme?

e.g.
https://goreportcard.com/report/github.com/smartystreets/goconvey
https://gocover.io/github.com/smartystreets/goconvey

**Comment by riannucci** [comment]
I think it's more a matter of GoConvey's own project coherence than anything to do with codebeat itself. Otherwise our readme would just look like http://shields.io/ :)

**Pull request closed without merging**
