### PR TITLE
Add simple update script and CI check for 3rd party libs.

### PR DESCRIPTION
**Pull request by riannucci**
This should make updates to .url files safer.

### CODE REVIEW

**Comment by riannucci** [comment]
@SunSparc heyo; It looks like this repo never got moved to travis-ci.com, and I don't have permission to set this up (and you seem to be currently attached to smartystreets, which owns this repo :)).

There are some long-standing javascript CVE pull requests which I'd like to merge, but because this repo currently includes the SOURCE of the javascript, I wanted some extra assurance that the checked-in js files actually correspond to what's in the .url files next to them. However this only works if Travis can actually Do The Thing™️ :).

Please let me know if I should bug someone else to do this!

Thanks,
Robbie

**Comment by SunSparc** [comment]
Hmm... that is confusing. I was looking on their pricing page, which only shows a free trial: https://www.travis-ci.com/pricing/

Then I found this page that shows an actual free plan: https://app.travis-ci.com/plans

Travis integration is now installed for `goconvey`.

**Comment by riannucci** [comment]
Thanks!!

**Comment by riannucci** [comment]
I'll upload another PR and see if something happens

**Pull request merged**
