### PR TITLE
Fix #4 by introducing optional test randomization

### LINKED ISSUE #4: Randomize execution of sibling scopes/resets
This is to drive out temporal couplings between tests.  Technically, the setup and teardown methods should be enough to do this but you just never know...

I think this will be a command line option that is enabled by default and can be disabled (which is how some of the unit tests can avoid being broken by this new feature).

### PR DESCRIPTION
**Pull request by riannucci**
So... that wasn't too bad either :) However, the test output (both story and json) are basically garbled junk :(.

What's the right thing to do with reporting? I could:
  1. buffer everything till the end and emit it in a stable sort order
  1. stream the output (but emit stories multiple times)
  1. ???

1 is pretty explanatory

2 would be something like:
```go
Convey("A", t, func() {
  Convey("B", func() {
    Convey("C", nil)
    Convey("D", nil)
  })  
  Convey("F", func() {
    Convey("G", nil)
  })
})
```

Could emit:
```
A
  B
    C
  F
    G
  B
    D
```
(assuming that's how they randomized).

Or is there another idea?

### CODE REVIEW

**Comment by riannucci** [comment]
Bump :)

Any interest in getting this one landed? I'd be willing to work on some of the protocol changes if that'll help.

R

**Comment by mdwhatcott** [comment]
Yes, I do have interest in this PR (sorry!!). Looks like we just need to get the seed to be displayed more discreetly (and only once per package). 

I'll be honest in saying that I won't be able to get to this anytime soon. At SmartyStreets we find GoConvey to be wonderfully useful and have declared the project "feature-complete" as it currently stands so other projects are crowding in. As for me personally: `familyMemberCount++` so I'm otherwise engaged outside of work at the present time. But you are certainly welcome to hack on the server for the web UI, if my babblings in previous comments (above) made any sense.

**Comment by riannucci** [comment]
Ah ha! :grinning: 

Ok, I'll see what I can do for the UI, etc. I'm a bit less-well-versed in the UI side of things so I may stumble about some...

And congratulations on your recent family addition!!! :smile:

**Comment by mdwhatcott** [comment]
Thanks--and good luck.

**Comment by mdwhatcott** [comment]
@riannucci - I just pulled this down again to see about getting it merged. Is this output correct?

```
mike@Michael:~/src/github.com/smartystreets/goconvey/examples [riannucci-randomize !?]

 • go test -v -randomize-tests=true -random-seed=42 -run=TestIntegerManipulation
=== RUN TestIntegerManipulation
Random Seed
  42
Given a starting integer value
  When incremented
    The value should NOT be what it used to be ✔
  When decremented
  When incremented
    The value should be greater by one ✔
  When decremented
    The value should NOT be what it used to be ✔
    The value should be lesser by one ✔


  4 assertions thus far

--- PASS: TestIntegerManipulation (0.00s)
PASS
ok  	github.com/smartystreets/goconvey/examples	0.006s


```

**Comment by riannucci** [comment]
Yeah I think that looks about right. I think I wrote some tests for this as well which pin various seeds and record the randomized order, so if the tests are passing, then I think it's still working.

It basically prints the full hierarchy of path-to-test for every test, but then de-duplicates identical paths in the printer. So really it's doing:

```
A
  B
    D
A
  B
    C
```

but it'll print

```
A
  B
    D
    C
```

**Comment by riannucci** [comment]
(and sorry about never getting around to doing the UI bits for this... I got stuck on some other projects :/)

**Comment by mdwhatcott** [comment]
No worries about not getting to the UI, I've been busy too.

There seems to be a dangling "`When decremented`" line near the middle of the output. I'm having a hard time mapping that output to a randomized, yet viable execution order, but it may just be my lack of understanding, not a bug--not sure.

**Comment by riannucci** [comment]
Oh! So I see... that is weird. I don't think I would expect that... it shouldn't be entering that Convey block if it doesn't intend on executing one of the leaf blocks inside of it. It may be a bug in the way that it's picking the next suite to run (which is in the `picker` logic)

**Comment by mdwhatcott** [comment]
I don't think I'll ever get around to smoothing this out and getting the UI working. Personally, I've moved on to a more simple test framework and runner but if someone wants to finish this we can merge it.

**Comment by dencold** [comment]
@mdwhatcott out of curiosity, what framework/runner have you moved on to? I'd be interested to know. Thanks!

**Comment by mdwhatcott** [comment]
@dencold

[gunit](https://github.com/smartystreets/gunit) is the latest library.

For very simple tests I just use the standard `"testing"` package with the [assertions](https://github.com/smartystreets/assertions/blob/master/doc.go#L34) package.

[scantest](https://github.com/smartystreets/scantest) is the latest test runner.

GoConvey is still awesome, I just really enjoy tinkering with different approaches to testing so I'll probably never be content for too long with any single framework...

**Comment by dencold** [comment]
@mdwhatcott got it, thanks so much for sharing. Really appreciate all your work on these types of projects. Keep hacking! :)

**Comment by mdwhatcott** [comment]
Thanks for the encouragement @dencold!

**Pull request closed without merging**
