### PR TITLE
Unminify bundled javascripts

### LINKED ISSUE #363: source-less minified javascripts
`web/client` contains source-less minified javascripts. Effectively minified code is equivalent of pre-compiled binary -- un-readable, non-modifiable and non-distributable in Debian.
It is a bad practice to commit binaries to VCS. 
Please replace all minified files with their original (non-minified) sources.

Read more in https://wiki.debian.org/onlyjob/no-minification

Thanks.

### PR DESCRIPTION
**Pull request by onlyjob**
Mostly fixes #363. All what's left to unpack is `font-awesome.min.css` and `jquery-ui-1_10_3-custom.min.js` but I do not know how jquery-ui was generated. Maybe switch to standard (not custom) build? Someone please take care of the rest. Cheers.

### CODE REVIEW

**Comment by mdwhatcott** [comment]
Is this "ready to merge" in your opinion or are there additional steps for someone else to take before this should be merged?

**Comment by onlyjob** [comment]
I think it should be safe to merge.

**Comment by onlyjob** [comment]
Thanks!

**Comment by mdwhatcott** [comment]
There have been a few issues filed related to javascript references and other things in the UI not functioning. I suspect it's related to this pull request (and the other one submitted to finish un-minifying the javascript).

Here are the recent issues:

- https://github.com/smartystreets/goconvey/issues/399
- https://github.com/smartystreets/goconvey/issues/400

I'm contemplating reverting this change unless it can be fixed.

**Comment by onlyjob** [comment]
> I'm contemplating reverting this change unless it can be fixed.

That would be most unfortunate... :( 
Please do not revert un-minification.
Maybe downgrading markup.js, moment.js or taboverride.js could help?

Those issues could be real bugs like the one we found when we upgraded fonts-awesome.
If those issues are regressions in upgraded 3rd party javascripts then sooner or later someone would have to investigate anyway...

**Comment by onlyjob** [comment]
Nobody could know what really was in those minified files we've replaced. Un-minification was necessary...

**Pull request merged**
