### PR TITLE
Add WorkDir Option

### PR DESCRIPTION
**Pull request by mopemope**
Add WorkDir Option.

### CODE REVIEW

**Comment by mdwhatcott** [comment]
Thanks for the contribution! Just curious, what is the behavior when the value supplied to `workDir` is not an existing directory?

**Comment by mopemope** [comment]
Ah I missed it.
I tried it.

## not exists directory

```
$  goconvey -workDir=/xxx
2015/07/07 23:25:09 goconvey.go:57: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2015/07/07 23:25:09 goconvey.go:185: Go cover tool is not installed or not accessible: `go get golang.org/x/tools/cmd/cover`
2015/07/07 23:25:09 tester.go:19: Now configured to test 10 packages concurrently.
2015/07/07 23:25:09 goconvey.go:146: Serving HTTP at: http://127.0.0.1:8080
```

## permission denied

```
$ goconvey -workDir=/root
2015/07/07 23:27:01 goconvey.go:57: Initial configuration: [host: 127.0.0.1] [port: 8080] [poll: 250ms] [cover: true]
2015/07/07 23:27:01 goconvey.go:185: Go cover tool is not installed or not accessible: `go get golang.org/x/tools/cmd/cover`
2015/07/07 23:27:01 tester.go:19: Now configured to test 10 packages concurrently.
2015/07/07 23:27:01 goconvey.go:146: Serving HTTP at: http://127.0.0.1:8080
2015/07/07 23:27:01 integration.go:120: File system state modified, publishing current folders... 0 1
2015/07/07 23:27:01 goconvey.go:93: Received request from watcher to execute tests...
2015/07/07 23:27:01 executor.go:69: Executor status: 'executing'
2015/07/07 23:27:01 coordinator.go:46: Executing concurrent tests: .
2015/07/07 23:27:01 parser.go:24: [test run aborted unexpectedly]: .
2015/07/07 23:27:01 executor.go:69: Executor status: 'idle'
```

What should i do ?

**Comment by mdwhatcott** [comment]
Do a check to see that the directory exists. Something like this:

http://stackoverflow.com/questions/10510691/how-to-check-whether-a-file-or-directory-denoted-by-a-path-exists-in-golang

As for permissions, I'm not sure if anything needs to be done. I think most users run the tool on their code directories, and they probably already have the correct permissions set.

**Comment by mopemope** [comment]
Thank you for the advice.
Added check working directory path.

**Comment by mdwhatcott** [comment]
Great. Now, the `main` and `coverToolInstalled` functions are getting pretty lengthy. Could the logic that sets the `workDir` and `working` variables be extracted to functions?

**Comment by mopemope** [comment]
Yes.
Could you  review my code  ?

**Pull request merged**
