### PR TITLE
Unminify

### LINKED ISSUE #363: source-less minified javascripts
`web/client` contains source-less minified javascripts. Effectively minified code is equivalent of pre-compiled binary -- un-readable, non-modifiable and non-distributable in Debian.
It is a bad practice to commit binaries to VCS. 
Please replace all minified files with their original (non-minified) sources.

Read more in https://wiki.debian.org/onlyjob/no-minification

Thanks.

### PR DESCRIPTION
**Pull request by onlyjob**
Remaining changes to close #363 (not tested but should be safe).

### CODE REVIEW

**Comment by onlyjob** [comment]
Thanks! :)

**Comment by yeka** [comment]
Hi @onlyjob,
This PR breaks the icons in web UI.
It requesting for `/fonts/fontawesome-webfont.*`, yet the fonts is not there.
Seems that it's been moved to `/fonts/FontAwesome/fontawesome-webfont.*`

**Comment by onlyjob** [comment]
Sorry for troubles. I'm not sure where did it came from. During update all reasonable precautions were taken to avoid disruptive changes i.e. location of files did not change.
However I guess it could be either difference between font-awesome 4.1 and 4.5 or locally customised `font-awesome.min.css` that was replaced on upgrade...
Unfortunately I'm unable to test so perhaps this problem could be fixed by moving files where they are expected to be?

**Comment by onlyjob** [comment]
Just as I thought, path to `/fonts/FontAwesome` was in the old CSS file. To use pristine font-awesome CSS file I'd move awesome-fonts to `fonts/` from `fonts/FontAwesome/`.

**Comment by onlyjob** [comment]
Interesting context: as I suspected old `font-awesome.min.css` was customised as it does not match [original CSS](https://github.com/FortAwesome/Font-Awesome/tree/4.1.0/css) at least in regards to path. I recommend to use pristine (i.e. original) CSS to avoid burden of maintaining customisations and upgrade bugs like this one... There are two ways to fix the problem -- either relocate `font-awesome.css` or font files. What do you prefer, @mdwhatcott?

**Comment by onlyjob** [comment]
Should be fixed by #395. Please review.

**Pull request merged**
