### PR TITLE
Conveniently launch browser in macOS

### PR DESCRIPTION
**Pull request by wallclockbuilder**
This PR lets goconvey conveniently launch the browser on startup. I find this useful because I don't have to manually open the browser everytime I run goconvey.

### CODE REVIEW

**Comment by casimir** [comment]
Correct me if I'm wrong but `open` will only work on OSX. You should use `xdg-open` for Linux (BSD?) and `start` for Windows.

**Comment by wallclockbuilder** [comment]
You're right. Open will only work for OSX.

Thats all I have access to for testing at the moment. 

Perhaps someone running a windows system will be better qualified to implement and test the windows version. Same for Linux.

**Comment by wallclockbuilder** [comment]
Updated the title. This PR is for OSX. I've opened issues for Windows and Linux versions.

**Comment by mdwhatcott** [comment]
One other scenario to consider: Sometimes I run GoConvey from within a vagrant (virtual machine) but the browser is run from the host.

**Comment by wallclockbuilder** [comment]
Any suggestions for improving the User Experience in your scenario?

**Comment by mdwhatcott** [comment]
How about this: Make launching the browser available for users running goconvey on `darwin` depending on a command line flag (`-browser`). If users on other platforms feel strongly about implementing the launch behavior they will contribute extensions to the behavior.

```
func flags() {
    ...
    flag.BoolVar(&browser, "browser", false, "When set, launch the web UI using default web browser at http://host:port (currently only supported on MacOS).")
    ...
}

...

func main() {
    ...
    launchBrowser()
    serveHTTP(server)
}

func launchBrowser() {
    if !browser {
        return
    }
    if runtime.GOOS != "darwin" {
        return
    }

    log.Printf("Launching browser on %s:%d", host, port)

	url := fmt.Sprintf("http://%s:%d", host, port)
	cmd := exec.Command("open", url)

	output, err := cmd.CombinedOutput()
	if err != nil {
		fmt.Println(err)
	}
	log.Println(string(output))
}

var (
    ...
    browser bool // defined with all other other flags
    ...
)
```

BTW, I don't think this behavior merits separate files for different os implementations.

**Comment by mdwhatcott** [comment]
Actually, no flag is needed. We can attempt the `open` command on `darwin` every time--it's not a big deal if fails.

```
func launchBrowser() {
    if runtime.GOOS != "darwin" {
        return
    }

    log.Printf("Launching browser on %s:%d", host, port)

    url := fmt.Sprintf("http://%s:%d", host, port)
    cmd := exec.Command("open", url)

    output, err := cmd.CombinedOutput()
    if err != nil {
        fmt.Println(err)
    }
    log.Println(string(output))
}
```

**Comment by casimir** [comment]
Why not just handle every OS explicitly? Something like [this](http://play.golang.org/p/tagX7sgOQj)?

**Comment by mdwhatcott** [comment]
Fine by me @casimir.

**Comment by wallclockbuilder** [comment]
@mdwhatcott @casimir 
Fixed in latest commit.
Thanks!

**Comment by casimir** [comment]
:+1:

**Pull request merged**
