### PR TITLE
Stop keydown propagation from input elements, but don't suppress.

### PR DESCRIPTION
**Pull request by logan**
This seems to work for me.

### CODE REVIEW

**Comment by mdwhatcott** [comment]
One solution would also be to get rid of support for keyboard shortcuts altogether. Would anyone be opposed to that as a solution?

**Comment by logan** [comment]
I didn't even know there were keyboard shortcuts until I tracked down why I couldn't edit the path. :P

**Comment by mdwhatcott** [comment]
Yeah, I thought I would use them but I rarely do. I'll think a bit more on this.

**Comment by logan** [comment]
Have you decided which way to proceed with fixing this bug? If you're not ready to remove the keyboard shortcuts yet, then this change should work.

**Comment by mdwhatcott** [comment]
I'd like to get rid of the keyboard shortcuts. Just haven't got to it. PR anyone?

**Comment by logan** [comment]
Thanks!

**Pull request merged**
