### PR TITLE
Add code for parsing format that ginkgo tests emit

### PR DESCRIPTION
**Pull request by msabramo**
Fixes: https://github.com/smartystreets/goconvey/issues/487

Cc: @JoyPeterson, @homanchou

### CODE REVIEW

**Comment by buzzdan** [comment]
any news on that issue ?

**Comment by riannucci** [comment]
This needs to pass the tests first; I'd also love to see some new tests to cover this format.

**Comment by msabramo** [comment]
I fixed the failing test by making the code be a little stricter about what it considers to be valid Ginkgo output.

**Comment by msabramo** [comment]
I added some tests in 69af19f.

**Comment by amanhigh** [comment]
Can we merge this one. I love goconvey ui but want to make it work with ginkgo.

**Comment by riannucci** [comment]
Wow I really missed that test update...

**Comment by riannucci** [comment]
Sorry about the delay!

**Pull request merged**
