### PR TITLE
Update test cover tool install info

### LINKED ISSUE #356: Outdated cover tool error message
The following line: https://github.com/smartystreets/goconvey/blob/aa2f5dd3546751f4d6be93cb58e906023324664c/goconvey.go#L275, points to `golang.org/x/tools/cmd/cover` to install the cover tool. However since Go 1.5, it's been deprecated and has moved to the main repository in `/src/cmd/cover`. People need to run `go install` from their and it works just fine.

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Fixes #356.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
I'm not sure which test I broke, and why only on tip. Anyone have a clue?

**Comment by Thomasdezeeuw** [comment]
Found it on line 463 of the output, it points to https://github.com/smartystreets/goconvey/blob/master/web/server/executor/tester_test.go#L175. But I didn't change that.

**Comment by mdwhatcott** [comment]
There are several (intermittent) broken tests as of Go 1.5. It wasn't you @Thomasdezeeuw.

**Comment by Thomasdezeeuw** [comment]
Good to hear.

**Pull request merged**
