### PR TITLE
SoMsg

### LINKED ISSUE #355: Ability to specify comment when asserting with So()
When checking if multiple fields in output struct are correct it would be useful to have ability to add comment to So() instead of just getting a line number of failed assert eg.

```
tested, err := NewHostFromMap(m)
    Convey("HostFromMap", t, func() {
        So(err, ShouldEqual, nil)
        So(tested.Hostname, ShouldEqual, m["host_name"])
        So(tested.State, ShouldEqual, "WARNING")
        So(tested.PreviousState, ShouldEqual, "OK")
        So(tested.CheckMessage, ShouldEqual, "DUMMY CHECK WARNING")
        ...
```

will just generate failures with only line number as an info, to get meaningful feedback I have to use much more verbose (and IMO much less readable) format:

```
tested, err := NewServiceFromMap(m)
Convey("ServiceFromMap", t, func() {
    Convey("no err", func() {
        So(err, ShouldEqual, nil)
    })
    Convey("Hostname", func() {
        So(tested.Hostname, ShouldEqual, m["host_name"])
    })
    Convey("Description", func() {
        So(tested.Description, ShouldEqual, m["service_description"])
    })
    Convey("State", func() {
        So(tested.State, ShouldEqual, "WARNING")
    })
    ...
```

It would be nice if it would be possible just to have something like

```
        So(tested.Hostname, ShouldEqual, m["host_name"], "Hostname")
        So(tested.State, ShouldEqual, "WARNING", "State")
```

and have that last field as a comment next to filename:line

### PR DESCRIPTION
**Pull request by kormat**
Adds a variant of So() that allows you to specify a message that is
reported on error.

Fixes #355

---

This change is [Reviewable](https://reviewable.io/reviews/smartystreets/goconvey/451)

### CODE REVIEW

**Comment by kormat** [comment]
Ping?

**Comment by kormat** [comment]
Ping?

**Comment by kormat** [comment]
We've been using this for the past 1.5+ years with no problems. I've just rebased it on master, in case there's a chance it could get merged now :)

**Comment by riannucci** [comment]
Hi :)

What does this look like? I'm not sure about creating a new scope on failure (as opposed to just prepending `msg` to the report)

**Pull request merged**
